name: Docker Image CI

on:
  release:
    types: [ published ]

jobs:

  build_push:
    name: Build and push Docker image to GitHub Packages

    runs-on: ubuntu-latest

    steps:
      -
        # Use Docker Buildx
        # See https://github.com/marketplace/actions/docker-setup-buildx#with-qemu
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Retrieve version tag
        # See https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#release
        # See https://stackoverflow.com/a/9533099/2427596
        # See https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#setting-an-environment-variable
        run: echo "TAG_VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV
      -
        name: Build and publish Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          platforms: amd64,arm64
          push: true
          tags: |
            unfoldingword/${{ github.repository }}:${{ env.TAG_VERSION }}
            unfoldingword/${{ github.repository }}:latest
